// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdHpZbCa9mECHnxZViK0AtBNyk3X_3ues',
    appId: '1:986819287695:web:793cc1c9336e1dd5752efa',
    messagingSenderId: '986819287695',
    projectId: 'bawoh1-test1',
    authDomain: 'bawoh1-test1.firebaseapp.com',
    storageBucket: 'bawoh1-test1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACXJmFnlvtSHqlMo_zPBGOw8qMU5rVjyM',
    appId: '1:986819287695:android:ff06927ebddb7b7f752efa',
    messagingSenderId: '986819287695',
    projectId: 'bawoh1-test1',
    storageBucket: 'bawoh1-test1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfiz_3sJFFaCCt_oRQig4Nin8vkvrUpLY',
    appId: '1:986819287695:ios:051749df42c81794752efa',
    messagingSenderId: '986819287695',
    projectId: 'bawoh1-test1',
    storageBucket: 'bawoh1-test1.firebasestorage.app',
    iosBundleId: 'com.example.tropicaguideApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfiz_3sJFFaCCt_oRQig4Nin8vkvrUpLY',
    appId: '1:986819287695:ios:051749df42c81794752efa',
    messagingSenderId: '986819287695',
    projectId: 'bawoh1-test1',
    storageBucket: 'bawoh1-test1.firebasestorage.app',
    iosBundleId: 'com.example.tropicaguideApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdHpZbCa9mECHnxZViK0AtBNyk3X_3ues',
    appId: '1:986819287695:web:905d05dd03160139752efa',
    messagingSenderId: '986819287695',
    projectId: 'bawoh1-test1',
    authDomain: 'bawoh1-test1.firebaseapp.com',
    storageBucket: 'bawoh1-test1.firebasestorage.app',
  );
}
